from selenium import webdriver
from selenium.webdriver.common.by import By
import time
driver = webdriver.Chrome()
driver.get("https://abzmvcapp-chanad.azurewebsites.net/")
driver.maximize_window()
driver.find_element(By.XPATH,"/html/body/header/nav/div/div/ul[2]/li[2]/a").click()
email=driver.find_element(By.ID,"Input_Email").send_keys("konnegarishivani09@gmail.com")
password=driver.find_element(By.ID,"Input_Password").send_keys("Shiv@ni032002")
login_button=driver.find_element(By.ID,"login-submit").click()
time.sleep(3)
query_response=driver.find_element(By.XPATH,"/html/body/header/nav/div/div/ul[1]/li[11]/a").click()
time.sleep(2)
create_new=driver.find_element(By.XPATH,"/html/body/div/main/p/a").click()
query_id=driver.find_element(By.ID,"QueryID").send_keys("Qu0000123412")
SrNo=driver.find_element(By.ID,"SrNo").send_keys("0000000021")
agent_id=driver.find_element(By.ID,"AgentID").send_keys("AG00001042")
Description=driver.find_element(By.ID,"Description").send_keys("I have a comprehensive policy for my 2023 Tesla Model 3. I am interested in adding a tire protection add-on and a personal accident cover. Could you provide me with details on how this will impact my premium?")
ResponseDate=driver.find_element(By.ID,"ResponseDate").send_keys("01/01/2025  12:00am")
create_button=driver.find_element(By.XPATH,"/html/body/div/main/div[1]/div/form/div[6]/input").click()
time.sleep(3)
qid_err=driver.find_element(By.XPATH,"/html/body/div/main/div[1]/div")
print("Query Id must be 10 characters")